export const clerkAppearance = {
  variables: {
    colorPrimary: "#3b82f6",
    colorDanger: "#f87171",
    colorSuccess: "#4ade80",
    colorWarning: "#fbbf24",
    colorBackground: "#0f172a",
    colorInputBackground: "#f1f5f9",
    colorInputText: "#0f172a",
    colorText: "#f8fafc",
    colorTextSecondary: "#94a3b8",
    colorTextOnPrimaryBackground: "#ffffff",
    colorNeutral: "#cbd5e1",
    colorForeground: "#f8fafc",
    colorMutedForeground: "#94a3b8",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-inter), system-ui, sans-serif",
    fontSize: "0.9375rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "w-full bg-[#0f172a] border border-white/15 shadow-2xl rounded-2xl",
    header: "gap-2",
    headerTitle: "!text-slate-50 text-2xl font-bold tracking-tight",
    headerSubtitle: "!text-slate-400 text-sm leading-relaxed",
    socialButtonsBlockButton:
      "border border-white/15 bg-white/5 !text-slate-100 hover:bg-white/10 font-medium",
    socialButtonsBlockButtonText: "!text-slate-100 font-medium",
    formButtonPrimary:
      "bg-primary hover:bg-primary/90 !text-white font-semibold shadow-lg shadow-primary/25 normal-case",
    formFieldInput:
      "bg-slate-100 border-slate-300 !text-slate-900 placeholder:text-slate-500 focus:border-primary/60 !pr-11 w-full",
    formFieldInputGroup: "relative flex w-full items-stretch",
    formFieldLabel: "!text-slate-200 font-medium text-sm",
    formFieldHintText: "!text-slate-400 text-xs",
    formFieldSuccessText: "!text-emerald-400 text-xs",
    formFieldErrorText: "!text-red-400 text-xs",
    formFieldInputShowPasswordButton:
      "!text-slate-600 hover:!text-slate-900 opacity-100 flex items-center justify-center min-w-8 min-h-8 shrink-0 inset-y-0 my-auto",
    formFieldInputShowPasswordIcon: "!text-slate-600 w-4 h-4",
    footer: "bg-transparent",
    footerActionText: "!text-slate-400 text-sm",
    footerActionLink: "!text-[#93c5fd] hover:!text-[#bfdbfe] font-semibold",
    footerPages: "!text-slate-500",
    footerPagesLink: "!text-slate-400",
    identityPreviewText: "!text-slate-200",
    identityPreviewEditButton: "!text-[#93c5fd] hover:!text-[#bfdbfe]",
    formResendCodeLink: "!text-[#93c5fd] hover:!text-[#bfdbfe] font-medium",
    otpCodeFieldInput:
      "border-white/15 bg-slate-100 !text-slate-900 text-lg font-semibold tracking-widest",
    dividerLine: "bg-white/15",
    dividerText: "!text-slate-400 text-xs uppercase tracking-wide",
    alertText: "!text-slate-200",
    alert: "border-white/10 bg-white/5",
    backLink: "!text-slate-300 hover:!text-slate-100",
    navbarButton: "!text-slate-300 hover:!text-slate-100",
    formHeaderTitle: "!text-slate-50",
    formHeaderSubtitle: "!text-slate-400",
    alternativeMethodsBlockButton: "!text-slate-200 border-white/15 hover:bg-white/5",
    logoBox: "hidden",
    main: "gap-6",
    form: "gap-5",
    devModeNotice: "!text-amber-400/90",
  },
};
